version: '3.8'

services:

# ======================
  # DATABASES
  # ======================

  restaurant-db:
    image: mysql:8
    container_name: restaurant-db
    environment:
      MYSQL_ROOT_PASSWORD: rahasia123 # (Sesuaikan dengan .env Anda)
      MYSQL_DATABASE: restaurant_db
    ports:
      - "3307:3306"
    volumes:
      - restaurant-data:/var/lib/mysql
      - ./database/restaurant.sql:/docker-entrypoint-initdb.d/restaurant.sql

  order-db:
    image: mysql:8
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: rahasia123 # (Sesuaikan dengan .env Anda)
      MYSQL_DATABASE: order_db
    ports:
      - "3319:3306"
    volumes:
      - order-data:/var/lib/mysql
      - ./database/order.sql:/docker-entrypoint-initdb.d/order.sql

  delivery-db:
    image: mysql:8
    container_name: delivery-db
    environment:
      MYSQL_ROOT_PASSWORD: rahasia123 # (Sesuaikan dengan .env Anda)
      MYSQL_DATABASE: delivery_db
    ports:
      - "3314:3306"
    volumes:
      - delivery-data:/var/lib/mysql
      - ./database/delivery.sql:/docker-entrypoint-initdb.d/delivery.sql

  # ======================
  # SERVICES
  # ======================

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "3315:3001"
    depends_on:
      - restaurant-db
    env_file:
      - ./restaurant-service/.env
    environment:
      - DB_HOST=restaurant-db

  order-service:
    build: ./order-service
    ports:
      - "3316:3002"
    depends_on:          
      - order-db         
    env_file:
      - ./order-service/.env
    environment:         
      - DB_HOST=order-db 

  payment-service:
    build: ./payment-service
    ports:
      - "3317:3003"
    env_file:
      - ./payment-service/.env
    environment:
      - SUPABASE_URL=https://gibhtqbyofoejicljrhd.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpYmh0cWJ5b2ZvZWppY2xqcmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczNjg4ODMsImV4cCI6MjA5Mjk0NDg4M30.Bt_iqIjdTcMiQa0oAP5UAcQdKm3ZKgMevOBEocp-jiU

  delivery-service:
    build: ./delivery-service
    ports:
      - "3318:3004"
    depends_on:
      - delivery-db
    env_file:
      - ./delivery-service/.env
    environment:
      - DB_HOST=delivery-db

volumes:
  restaurant-data:
  order-data:
  delivery-data: